name: Ruby Gem release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 3.0.2
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 3.0.2
      - run: bundle install
        working-directory: ./sdk/src/login_radius


      - name: Build Ruby Gem
        run: |
         gem build login_radius.gemspec
         working-directory: ./sdk/src/login_radius
         env:
          GEM_HOST_API_KEY: "${{secrets.GEM_HOST_API_KEY}}"
      - name: Build Ruby Gem
        run: |
          gem push login_radius-11.2.0.gem(login_radius.gemspec)
          working-directory: ./sdk/src/login_radius
        
